services:
  proxy:
    build:
      context: .
      dockerfile: Dockerfile.proxy
    ports:
      - '8080:80'
      - '8443:443'
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - '3000:3000'
    volumes:
      - prod-db:/app/data
    env_file:
      - 'packages/server/.env.production'
    restart: unless-stopped
volumes:
  prod-db:
    driver: local
