services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - prod-db:/app/data
    restart: unless-stopped
    environment:
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID:?GITHUB_CLIENT_ID is required}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET:?GITHUB_CLIENT_SECRET is required}
      DATABASE_URL: ${DATABASE_URL:-file:./dev.db} #
volumes:
  prod-db:
    driver: local
